name: Deploy react base app

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
   
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install # will run `yarn install` command
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build # will run `yarn build` command
    - name: Install Surge
      run: npm install -g surge
    - name: Run surge
      run: surge ./build bootcamp2_reactBaseApp.surge.sh --token ${{ secrets.SURGE_TOKEN }}
      
      
      
      
      
      
      
      
      
      
      
      
      
